thads13 = read.csv('thads/thads2013n.txt')
thads11 = read.csv('thads/thads2011.txt')
thads = merge(thads13, thads11, all=TRUE)
thads = subset(thads, VALUE!=-6)
thads = subset(thads, TOTSAL!=-9)
thads = subset(thads, ZSMHC!=-6)
save(thads, file='thads.Rda')
