library(ggplot2)
ggplot(data=thads, aes(x=ZINC2, y=VALUE)) + geom_point()
ggplot(data=thads, aes(x=IPOV, y=VALUE)) + geom_point()
ggplot(data=thads, aes(x=APLMED, y=VALUE)) + geom_point()
ggplot(data=thads, aes(x=AGE1, y=VALUE)) + geom_point()
ggplot(data=thads, aes(x=factor(AGE1), y=VALUE)) + geom_violin()
ggplot(data=thads, aes(x=NUNITS, y=VALUE)) + geom_point()
ggplot(data=thads, aes(x=PER, y=VALUE)) + geom_point()
ggplot(data=thads, aes(x=factor(ROOMS), y=VALUE)) + geom_boxplot()
ggplot(data=thads, aes(x=BEDRMS, y=VALUE)) + geom_point()
ggplot(data=thads, aes(x=factor(BEDRMS), y=VALUE)) + geom_boxplot()
ggplot(data=thads, aes(x=TOTSAL, y=VALUE)) + geom_point()
ggplot(data=thads, aes(x=UTILITY, y=VALUE)) + geom_point()
ggplot(data=thads, aes(x=BUILT, y=VALUE)) + geom_point()
ggplot(data=thads, aes(x=factor(BUILT), y=VALUE)) + geom_boxplot()
ggplot(data=thads, aes(x=factor(METRO3), y=VALUE)) + geom_violin()
ggplot(data=thads, aes(x=factor(STRUCTURETYPE), y=VALUE)) + geom_boxplot()
